version: '2'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 8888:7070
    links:
      - db:db
    volumes:
      - .:/stock-service
    depends_on:
      - db

  db:
    restart: always
    image: percona:5.6
    environment:
      MYSQL_USER: pt
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: pt
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 33006:3306
    command: "mysqld --innodb_buffer_pool_size=1G --innodb_file_per_table=1 --innodb_read_io_threads=4 --innodb_write_io_threads=8 --innodb_buffer_pool_load_at_startup=ON --innodb_flush_method=O_DIRECT  --innodb_flush_log_at_trx_commit=0"
