version: '2'

services:
  php:
    restart: always
    working_dir: /var/www
    ports:
          - 10001:80
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf