version: '3'

services:
  web:
    image: nginx:alpine
    deploy:
      replicas: 3
    volumes:
        - .:/var/www
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 10001:80
    depends_on:
        - php
        - service-stock-mysql
  php:
    working_dir: /var/www
    image: vulukut/stock-service-php
    deploy:
      replicas: 3
    volumes:
      - .:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  service-stock-mysql:
    image: mysql:5.7
    volumes:
        - ./database.sql:/database.sql
    environment:
        - MYSQL_DATABASE=stock
        - MYSQL_ROOT_PASSWORD=root
    ports:
        - 3306:3306
    command: bash -c "sleep 65 && mysql -uroot -proot < database.sql"