version: '2'

services:
  web:
    image: nginx:alpine
    volumes:
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 10001:80
    restart: always
    depends_on:
        - php
        - service-stock-mysql
  php:
    restart: always
    working_dir: /var/www
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
  service-stock-mysql:
    image: mysql:5.7
    container_name: service-stock-mysql
    restart: always
    environment:
        - MYSQL_DATABASE=stock
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
    ports:
        - 3306:3306