version: '3'

services:
  web:
    image: nginx:alpine
    container_name: service-stock-web
    volumes:
        - .:/var/www
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 10001:80
    depends_on:
        - php
        - service-stock-mysql
  php:
    working_dir: /var/www
    container_name: service-stock-php
    image: vulukut:stock-service-php
    volumes:
      - .:/var/www
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
  service-stock-mysql:
    image: mysql:5.7
    container_name: service-stock-mysql
    volumes:
        - ./database.sql:/database.sql
    restart: always
    environment:
        - MYSQL_DATABASE=stock
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
    ports:
        - 3306:3306
    command: mysql -uroot -proot < database.sql