version: '2'

services:
  php:
    restart: always
    working_dir: /var/www
    container_name: service-stock-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www