version: '2'

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf